# Variables

@baseUrl = http://localhost:3333

# Health check

GET {{{baseUrl}}}/health

###

#GET rooms
# @name getRooms

GET {{baseUrl}}/rooms


###

# Create Room
# @name createRoom

POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name":"Sala de teste",
    "description":"Essa é uma sala de teste"
}

###
@roomId = {{createRoom.response.body.$.roomId}}

### 

# GET room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions


###

# Create Question
# @name createQuestion

POST {{baseUrl}}/rooms/ef46a644-2758-4f11-95ff-6ba6c0d2c90b/questions
Accept: application/json
Content-Type: application/json

{
    "question":"O que é react"
}